### PR TITLE
remove Slack link formatting

### PR DESCRIPTION
**Pull request by Raerten**
hello,
this commit can fix issue #9

### CODE REVIEW

**Comment by jimmycuadra** [comment]
Hi, and thanks for the pull request! I'd definitely like to get this issue fixed. I think we should follow the implementation of the Hubot adapter (maintained by Slack themselves) for removing the formatting from Slack messages. We'll want to make sure all of this behavior is verified with tests as well. I looked through the various GitHub issues and the Slack API documentation to find the resources needed to do this:

* [Slack message formatting](https://api.slack.com/docs/formatting)
* [hubot-slack's removeFormatting function](https://github.com/slackhq/hubot-slack/blob/3c915db7f1b1ae032bc046cf778372bb53e5337c/src/slack.coffee#L137)
* [test cases for the above function](https://github.com/slackhq/hubot-slack/blob/ea562aeadab3f9f58e8db6ee5e86a4a41509db6a/test/slack.coffee#L55)

I think the function is involved enough that it makes sense to put it into a separate method (or perhaps a separate object) rather than including the logic in `Lita::Adapters::Slack::MessageHandler#body`.

**Comment by legh** [comment]
Hi, I've made a change to be closer to hubot but it's a bit complicated because lack of channels mapping.
And in this case it's not fix #9 , e.g. we put 
> whois  google.com

and get

> whois http://google.com

the problim is in https://github.com/legh/lita-slack/commit/aed412a2f5005eea981edc15a039334a656debc1#diff-31e69e8d557842a5aeffa1436b76396bR76
because after unformat we'v got not what a user put in a chat.
I'd prefer to use here clean label.

What do you think?

**Comment by jimmycuadra** [comment]
Sorry for the slow response! This is looking pretty good. It will still need tests, and `Lita::Adapters::Slack::MessageHandler#body` is sufficiently complex that I think it deserves to be moved into a new class with each mutation in a separate method.

**Comment by legh** [comment]
Greate! I'll create new tests.

**Comment by freibuis** [comment]
Is this ever going to be merged? 
in my custom plugins I have been hacking it all over the place to remove formatting. 
it would be good if this was implemented from the slack adapter it self.

**Comment by jimmycuadra** [comment]
Seems it's been abandoned, or just left stagnant, by the author. I agree that it's sorely needed. Another PR is welcome, though I will try to get to it soon myself.

**Comment by freibuis** [comment]
any way to nudge the slack devs to have clean/raw/unchanged message when talking to slack rtm api?
I think that undoing slacks formatting will cause grief any time slack api changes its mind with formatting.

side note, maybe only certain message formats.. like urls  <http://www.domain.com|www.domain.com>   ->  www.domain.com.au  this would prevent most plugins from breaking..  

thoughts?

**Comment by freibuis** [comment]
put my 2 cents into a pull request #35

**Comment by jimmycuadra** [comment]
This work was completed in #35. Thanks a bunch for getting us on the right track!

**Pull request closed without merging**
