### PR TITLE
Cast user profile values to string

### PR DESCRIPTION
**Pull request by byroot**
Fixes: https://github.com/kenjij/lita-slack/issues/57

It kinda suck to call `to_s` on an Array. but IMO it's still better than only passing a subset.

I tested it, it fixes the issue on boot.

@jimmycuadra @lhagemann @davetron5000 for review / test please.

### CODE REVIEW

**Comment by byroot** [comment]
uh, I have no idea why the build failed :s

**Comment by jimmycuadra** [comment]
WTF @ that build error. I'll dig into it as soon as I get a chance.

**Comment by jimmycuadra** [comment]
Thanks for the PR, but I decided to just revert the behavior change in 1.7.1. I should have been more careful about accepting that in the first place, for reasons discussed in #47 and #50. If custom code for saving Slack user metadata is desired, hook into the `:slack_user_created` event.

**Comment by davetron5000** [comment]
I'm a bit confused as this just seems to be `to_s`'ing what's coming out.  We are using a vanilla Slack install with nothing fancy, and Lita totally dies when sucking up the user data due to this issue.  Lita absolutely requires that the metadata be a single-depth hash of primitives (it forces this via `.to_a.flatten`, which turns empty arrays into missing [not nil] attributes and ultimately causes the redis client to blow up).

That is a long-winded way of saying "Don't we need this?"

**Comment by jimmycuadra** [comment]
No, because the behavior in 1.7.0 and 1.7.2 is to explicitly select the values from the profile data that are known to be scalar. The behavior in 1.7.1 just merged everything in, which we learned the hard way was not compatible with all possible future additions to the metadata provided by Slack.

**Comment by davetron5000** [comment]
OH, I see.  Thanks for the explanation.  I'll try that instead of my fork of lita and open a new issue if I see something.

**Pull request closed without merging**
