### PR TITLE
Defer the message handling so that slow handler to not freeze Lita

### PR DESCRIPTION
**Pull request by byroot**
@jimmycuadra 

This fixes both https://github.com/jimmycuadra/lita/pull/79 and https://github.com/jimmycuadra/lita/pull/77

### CODE REVIEW

**Comment by jimmycuadra** [comment]
Awesome! I'll test it out too. Thanks for doing this.

**Comment by jimmycuadra** [comment]
I just tried it out on my own Slack instance and it doesn't seem to have quite the right effect. Here's the handler I was running:

``` ruby
Lita.register_handler(:slow) do
  route /slow/i do |response|
    response.reply "slow message 1. another will appear after 5 seconds."
    sleep 5
    response.reply "slow message 2."
  end

  route /fast/i do |response|
    response.reply "fast message."
  end
end
```

On lita-slack master, sending the message "slow" will result in a 5 second delay, then both responses from the "slow" route showing up at once, as was reported in jimmycuadra/lita#77. If I send the message "slow fast" then all three responses appear after a 5 second delay. This is also consistent with the reported issue.

With the changes on this branch, I see slightly different behavior.Sending "slow" results in varying timings. Sometimes the first "slow" response comes right away, followed by the second "slow" response a few seconds later, but sometimes it behaves just like it does on master. Other times, there is a small delay before the first response, followed by another small delay before the second response. In all cases, the response from the "fast" route doesn't appear until after the second "slow" response, indicating that the routes are not being executed concurrently.

**Comment by jimmycuadra** [comment]
I tried adding an `EM.defer` block for outgoing messages:

``` ruby
def send_messages(channel, strings)
  strings.each do |string|
    EM.defer { websocket.send(safe_payload_for(channel, string)) }
  end
end
```

This seems to correct the behavior from jimmycuadra/lita#77, but not your issue, jimmycuadra/lita#79. That is, it causes responses from the "slow" right to show up with the correct timing consistently, but the "fast" response is still blocked until the "slow" route has completed.

**Comment by jimmycuadra** [comment]
The issue from jimmycuadra/lita#79 may in fact be an issue with Lita itself. `MessageHandler#handle` in lita-slack is just constructing the usual Lita objects to send off to `Lita::Robot#receive`, but the actual iteration through registered handlers and dispatch to matching routes happens inside Lita, where lita-slack has no ability to control the concurrency mechanism. It looks like Lita's dispatch system needs to expose some way for adapters to supply their own concurrency mechanism.

**Comment by byroot** [comment]
It works perfectly for me: 

capture d ecran 2015-02-27 a 09 08 14

**Comment by byroot** [comment]
> If I send the message "slow fast" then all three responses appear after a 5 second delay. 

Indeed this create a thread per incoming message, so if multiple routes match a single message they will be executed one after the other.

https://github.com/jimmycuadra/lita/pull/79 was actually solving that issue. It could be made optional with a `async: true` or something in the route options.

Actually we were talking about doing so for events yesterday, because we have an HTTP handler that receive webhooks from github and dispatch thems as event, and we don't want to wait to all the subscribers to the event to complete before acknowledging the webhook.

**Comment by jimmycuadra** [comment]
I released a new version of lita-slack, 1.1.1 which includes this change, which fixes jimmycuadra/lita#77. jimmycuadra/lita#79 will require a change to Lita to allow adapters to use their own concurrency mechanism during incoming message dispatch. Once that is complete, lita-slack can use it to fix the issue you originally reported.

**Pull request closed without merging**
