### PR TITLE
add attachments for parsing

### PR DESCRIPTION
**Pull request by ptqa**
Hi, I think it would be nice to parse text in attachments.

### CODE REVIEW

**Comment by jimmycuadra** [comment]
Thanks for the contribution! Would you mind adding a test case for this? I think attachments should be separated from the message by newlines instead of spaces, as well.

**Comment by ptqa** [comment]
@jimmycuadra ok, see updated commit. I have no experience with rspec, so I just copy-pasted similar test. Please check if it's ok.

**Comment by jimmycuadra** [comment]
Great! Thanks very much!

**Comment by ptqa** [comment]
@jimmycuadra please update gem, so I can use it without manual patching

**Comment by jimmycuadra** [comment]
Done: https://github.com/kenjij/lita-slack/releases/tag/v1.3.0

**Comment by ptqa** [comment]
@jimmycuadra many thanks!

**Pull request merged**
